#!/usr/bin/env python3
"""Generate avalanche-update.ks — install the Snowfall updater into the ISO.

Like the other gen-*.ks scripts, %post can't read the host's files, so the
plasmoid (metadata/QML/SVG), the two helper scripts, the launcher + autostart
.desktop entries, the app icon (base64), and the KWin frameless rule are all
baked into the kickstart text here.

Zero new packages: the runtime (plasmawindowed, QtQuick.Particles,
plasma5support, pkexec, dnf5) already ships on the KDE spin.

Run from anywhere: python3 scripts/gen-update-ks.py
"""
import base64
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PLASMOID = "/usr/share/plasma/plasmoids/org.avalanche.snowupdate"

out = []
a = out.append


def read(rel):
    with open(os.path.join(ROOT, rel)) as f:
        return f.read().rstrip("\n")


def emit_text(dest, src_rel, marker, mode=None):
    body = read(src_rel)
    assert marker not in body.splitlines(), f"marker {marker} collides in {src_rel}"
    a(f'mkdir -p "$(dirname "{dest}")"')
    a(f"cat > \"{dest}\" << '{marker}'")
    a(body)
    a(marker)
    if mode:
        a(f'chmod {mode} "{dest}"')
    a("")


def emit_png(dest, src_rel):
    with open(os.path.join(ROOT, src_rel), "rb") as f:
        data = f.read()
    b64 = base64.b64encode(data).decode()
    block = "\n".join(b64[i:i + 76] for i in range(0, len(b64), 76))
    assert base64.b64decode(block) == data, f"base64 round-trip failed for {src_rel}"
    a(f'mkdir -p "$(dirname "{dest}")"')
    a(f"# {src_rel} -> {dest} ({len(data)} bytes)")
    a(f"base64 -d > \"{dest}\" << 'B64EOF'")
    a(block)
    a("B64EOF")
    a("")


a("# avalanche-update.ks — Snowfall thematic system updater")
a("# GENERATED by scripts/gen-update-ks.py — do not edit by hand.")
a("#")
a("# Plasmoid org.avalanche.snowupdate, run via plasmawindowed; pending dnf5")
a("# updates shown as a snowstorm the user controls. Frameless (KWin rule), with")
a("# a once-a-day login autostart gate. Zero new packages.")
a("")
a("%post")
a("")
a("# ── Plasmoid package ──────────────────────────────────────────────────────")
emit_text(f"{PLASMOID}/metadata.json", "plasma/snowupdate/metadata.json", "AVALMETA")
emit_text(f"{PLASMOID}/contents/ui/main.qml",
          "plasma/snowupdate/contents/ui/main.qml", "AVALQML")
emit_text(f"{PLASMOID}/contents/images/snowboard.svg",
          "plasma/snowupdate/contents/images/snowboard.svg", "AVALSVG")

a("# ── Helper scripts (count / apply / daily gate) ───────────────────────────")
emit_text("/usr/local/bin/avalanche-update-run",
          "scripts/avalanche-update-run", "AVALRUN", mode="0755")
emit_text("/usr/local/bin/avalanche-update-check",
          "scripts/avalanche-update-check", "AVALCHK", mode="0755")

a("# ── App icon (avalanche-snowfall, hicolor) ────────────────────────────────")
for size in ("128x128", "256x256", "512x512"):
    px = size.split("x")[0]
    emit_png(f"/usr/share/icons/hicolor/{size}/apps/avalanche-snowfall.png",
             f"assets/icon/avalanche-icon-{px}.png")
a("gtk-update-icon-cache -f -t /usr/share/icons/hicolor 2>/dev/null || true")
a("")

a("# ── Launcher (menu) + autostart (once/day gate, system-wide) ──────────────")
emit_text("/usr/share/applications/avalanche-snowfall.desktop",
          "plasma/snowupdate/avalanche-snowfall.desktop", "AVALDESK")
emit_text("/etc/xdg/autostart/avalanche-snowfall-autostart.desktop",
          "plasma/snowupdate/avalanche-snowfall-autostart.desktop", "AVALAUTO")

a("# ── Frameless window (KWin rule matching the Snowfall window) ──────────────")
a('mkdir -p "$(dirname "/etc/xdg/kwinrulesrc")"')
a("cat > /etc/xdg/kwinrulesrc << 'AVALKWIN'")
a("[General]")
a("count=1")
a("rules=avalanche-snowfall")
a("")
a("[avalanche-snowfall]")
a("Description=Avalanche Snowfall — frameless")
a("noborder=true")
a("noborderrule=2")
a("title=Snowfall")
a("titlematch=1")
a("AVALKWIN")
a("")
a('echo "AVALANCHE: Snowfall updater installed (plasmoid + autostart + frameless rule)"')
a("%end")
a("")

with open(os.path.join(ROOT, "avalanche-update.ks"), "w") as f:
    f.write("\n".join(out))
print("wrote avalanche-update.ks")
