#!/usr/bin/env python3
"""Generate avalanche-effects.ks by embedding the compiled AvalancheDestroy plugin.

The .so is compiled on the VM by vm-rebuild.sh before the ISO build starts.
This script base64-encodes it and emits the %post block that installs it into
the assembled system — exactly the same pattern as gen-branding-ks.py for PNGs.

Run from the project root after building:
    python3 scripts/gen-effects-ks.py
"""
import base64
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUILD_DIR = os.path.join(ROOT, "kwin", "avalanchedestroy", "build")
OUT = os.path.join(ROOT, "avalanche-effects.ks")

SO_CANDIDATES = [
    os.path.join(BUILD_DIR, "kwin_effect_avalanchedestroy.so"),
    os.path.join(BUILD_DIR, "lib", "kwin_effect_avalanchedestroy.so"),
]
METADATA = os.path.join(ROOT, "kwin", "avalanchedestroy", "metadata.json")

PLUGIN_DEST = "/usr/lib64/qt6/plugins/kwin/effects/kwin_effect_avalanchedestroy.so"
META_DEST   = "/usr/share/kwin/effects/avalanchedestroy/metadata.json"


def b64_block(path):
    with open(path, "rb") as f:
        data = f.read()
    b64 = base64.b64encode(data).decode()
    lines = "\n".join(b64[i:i+76] for i in range(0, len(b64), 76))
    assert base64.b64decode(lines) == data, f"base64 round-trip failed for {path}"
    return lines, len(data)


def main():
    so_path = next((p for p in SO_CANDIDATES if os.path.exists(p)), None)
    if so_path is None:
        print("ERROR: compiled .so not found. Run the cmake build first.", file=sys.stderr)
        print("  Expected one of:", file=sys.stderr)
        for p in SO_CANDIDATES:
            print(f"    {p}", file=sys.stderr)
        sys.exit(1)

    so_b64, so_bytes = b64_block(so_path)

    with open(METADATA) as f:
        meta_content = f.read().rstrip("\n")

    lines = []
    lines.append("# avalanche-effects.ks — GENERATED by scripts/gen-effects-ks.py")
    lines.append("# Do not edit by hand. Edit kwin/avalanchedestroy/ source + rebuild.")
    lines.append("")
    lines.append("%post")
    lines.append("")
    lines.append("# ── AvalancheDestroy KWin effect plugin ──────────────────────────────────────")
    lines.append(f'mkdir -p "$(dirname "{PLUGIN_DEST}")"')
    lines.append(f"# kwin_effect_avalanchedestroy.so ({so_bytes} bytes)")
    lines.append(f"base64 -d > \"{PLUGIN_DEST}\" << 'B64EOF'")
    lines.append(so_b64)
    lines.append("B64EOF")
    lines.append(f'chmod 755 "{PLUGIN_DEST}"')
    lines.append("")
    lines.append(f'mkdir -p "$(dirname "{META_DEST}")"')
    lines.append(f"cat > \"{META_DEST}\" << 'TXTEOF'")
    lines.append(meta_content)
    lines.append("TXTEOF")
    lines.append("")
    lines.append("# ── Enable the effect system-wide ────────────────────────────────────────────")
    lines.append("mkdir -p /etc/xdg/kdedefaults")
    lines.append("cat >> /etc/xdg/kdedefaults/kwinrc << 'TXTEOF'")
    lines.append("")
    lines.append("[Plugins]")
    lines.append("kwin4_effect_avalanchedestroyEnabled=true")
    lines.append("TXTEOF")
    lines.append("")
    lines.append('echo "AVALANCHE: AvalancheDestroy KWin effect installed (avalanchedestroy)"')
    lines.append("")
    lines.append("%end")
    lines.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(lines))

    print(f"Wrote {OUT}")
    print(f"  Plugin: {so_bytes:,} bytes embedded, round-trip verified.")


if __name__ == "__main__":
    main()
