#!/usr/bin/env python3
"""Generate avalanche-grub.ks with embedded GRUB theme background.

Why a generator: the background PNG is a binary asset that must be base64-baked
into the kickstart heredoc (same reason gen-branding-ks.py exists). The GRUB
theme itself (theme.txt) is tiny text, embedded inline.

Theme applies to INSTALLED systems only — the live ISO boot menu is built by
lorax from its own templates and is not affected by GRUB_THEME or GRUB_DISTRIBUTOR.
"""
import base64
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, "assets")
OUT = os.path.join(ROOT, "avalanche-grub.ks")

BG_SRC = "avalanche-bootsplash-1920x1080.png"
THEME_DIR = "/boot/grub2/themes/avalanche"

# Dark alpine palette: deep blue bg, light text on menu entries.
# No custom fonts — GRUB uses its built-in unifont so no .pf2 files needed.
THEME_TXT = """\
# Avalanche OS GRUB theme
desktop-image: "background.png"
desktop-color: "#0A1628"
title-text: ""

+ boot_menu {
    left = 15%
    top = 28%
    width = 70%
    height = 44%
    item_color = "#C8D8E8"
    selected_item_color = "#FFFFFF"
    item_height = 28
    item_padding = 14
    item_spacing = 4
    scrollbar = false
}

+ label {
    left = 0
    top = 12%
    width = 100%
    align = "center"
    text = "Avalanche OS"
    color = "#E7EEF3"
}

+ label {
    id = "__timeout__"
    left = 0
    top = 76%
    width = 100%
    align = "center"
    color = "#6A8DA0"
    text = "Boot in %ds"
}
"""


def b64_block(path):
    with open(path, "rb") as f:
        data = f.read()
    b64 = base64.b64encode(data).decode()
    lines = "\n".join(b64[i:i + 76] for i in range(0, len(b64), 76))
    assert base64.b64decode(lines) == data, f"base64 round-trip failed for {path}"
    return lines, len(data)


def heredoc(out, dest, body):
    out.append(f'mkdir -p "$(dirname "{dest}")"')
    out.append(f'cat > "{dest}" << \'TXTEOF\'')
    out.append(body.rstrip("\n"))
    out.append("TXTEOF")
    out.append("")


def main():
    out = []
    out.append("# avalanche-grub.ks — GENERATED by scripts/gen-grub-ks.py")
    out.append("# Do not edit by hand. Edit scripts/gen-grub-ks.py then re-run it.")
    out.append("#")
    out.append("# Sets GRUB_DISTRIBUTOR and installs a visual GRUB theme.")
    out.append("# Theme applies to INSTALLED systems (not the live ISO boot menu).")
    out.append("")
    out.append("%post")
    out.append("")

    # ── GRUB_DISTRIBUTOR ──────────────────────────────────────────────────────
    out.append("# ── GRUB_DISTRIBUTOR ─────────────────────────────────────────────────────────")
    out.append("GRUBDEF=/etc/default/grub")
    out.append("")
    out.append('if [ -f "$GRUBDEF" ]; then')
    out.append("    if grep -q '^GRUB_DISTRIBUTOR=' \"$GRUBDEF\"; then")
    out.append('        sed -i \'s/^GRUB_DISTRIBUTOR=.*/GRUB_DISTRIBUTOR="Avalanche OS"/\' "$GRUBDEF"')
    out.append("    else")
    out.append('        echo \'GRUB_DISTRIBUTOR="Avalanche OS"\' >> "$GRUBDEF"')
    out.append("    fi")
    out.append("else")
    out.append('    echo \'GRUB_DISTRIBUTOR="Avalanche OS"\' > "$GRUBDEF"')
    out.append("fi")
    out.append("")

    # ── Visual theme ──────────────────────────────────────────────────────────
    out.append("# ── Visual theme ─────────────────────────────────────────────────────────────")
    out.append(f"mkdir -p {THEME_DIR}")
    out.append("")

    bg_path = os.path.join(ASSETS, BG_SRC)
    block, nbytes = b64_block(bg_path)
    out.append(f"# {BG_SRC} ({nbytes} bytes) -> {THEME_DIR}/background.png")
    out.append(f'base64 -d > "{THEME_DIR}/background.png" << \'B64EOF\'')
    out.append(block)
    out.append("B64EOF")
    out.append("")

    heredoc(out, f"{THEME_DIR}/theme.txt", THEME_TXT)

    # ── GRUB_THEME in /etc/default/grub ───────────────────────────────────────
    out.append("# ── GRUB_THEME ───────────────────────────────────────────────────────────────")
    out.append(f"THEME_LINE='GRUB_THEME={THEME_DIR}/theme.txt'")
    out.append('if grep -q \'^GRUB_THEME=\' "$GRUBDEF"; then')
    out.append('    sed -i "s|^GRUB_THEME=.*|$THEME_LINE|" "$GRUBDEF"')
    out.append("else")
    out.append('    echo "$THEME_LINE" >> "$GRUBDEF"')
    out.append("fi")
    out.append("")
    out.append('echo "AVALANCHE: GRUB theme -> $THEME_LINE"')
    out.append('grep "^GRUB_DISTRIBUTOR=\\|^GRUB_THEME=" "$GRUBDEF"')
    out.append("")
    out.append("%end")
    out.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(out))

    print(f"Wrote {OUT}")
    print(f"  Background: {BG_SRC} ({nbytes} bytes embedded, round-trip verified)")


if __name__ == "__main__":
    main()
