#!/usr/bin/env python3
"""Generate avalanche-terminal.ks — kitty as the default terminal (replaces Konsole).

The single source of truth for the kitty config is kitty.conf at the repo root;
%post can't read the host's files, so it's baked into the kickstart text here.

Run from anywhere: python3 scripts/gen-terminal-ks.py
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KITTY = os.path.join(ROOT, "kitty.conf")
OUT = os.path.join(ROOT, "avalanche-terminal.ks")

with open(KITTY) as f:
    kitty_conf = f.read().rstrip("\n")

out = []
a = out.append
a("# avalanche-terminal.ks — kitty as the default terminal (replaces Konsole)")
a("# GENERATED by scripts/gen-terminal-ks.py from kitty.conf — do not edit by hand.")
a("#")
a("# Cost: kitty ~15 MiB; jetbrains-mono-fonts a few MiB; removing konsole reclaims")
a("# ~10 MiB. Fedora's jetbrains-mono-fonts is NOT nerd-patched — kitty.conf uses")
a("# plain \"JetBrains Mono\" (standard Unicode prompt glyphs render fine).")
a("")
a("%packages")
a("kitty")
a("jetbrains-mono-fonts")
a("-konsole")
a("%end")
a("")
a("%post")
a("# ── kitty config for every new user ───────────────────────────────────────")
a("mkdir -p /etc/skel/.config/kitty")
a("cat > /etc/skel/.config/kitty/kitty.conf << 'KITTYEOF'")
a(kitty_conf)
a("KITTYEOF")
a("")
a("# ── make kitty the default terminal in KDE ────────────────────────────────")
a("kwriteconfig6 --file /etc/xdg/kdeglobals --group General --key TerminalApplication kitty")
a("kwriteconfig6 --file /etc/xdg/kdeglobals --group General --key TerminalService kitty.desktop")
a("")
a('echo "AVALANCHE: kitty installed as default terminal (konsole removed)"')
a("%end")
a("")

with open(OUT, "w") as f:
    f.write("\n".join(out))
print("wrote", OUT)
