#!/usr/bin/env python3
"""Generate avalanche-branding.ks with binary branding assets embedded.

Like gen-bootsplash-ks.py, %post can't read the host's assets/ dir, so any
binary (icons, wallpaper) must be base64-baked into the kickstart text. Each
block is verified to round-trip byte-for-byte before we trust it.

Embeds:
  - the logo icon (4 sizes) as the named icon `avalanche-logo-icon`, so the
    LOGO= field in os-release (Layer 1) finally resolves.
  - the dark wallpaper as a proper Plasma wallpaper package, wired up as the
    default desktop + lockscreen background for fresh sessions.

Run from anywhere; paths resolve relative to the project root.
"""
import base64
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, "assets")
OUT = os.path.join(ROOT, "avalanche-branding.ks")

# (source png, hicolor size dir) -> installed as avalanche-logo-icon.png
ICONS = [
    ("icon/avalanche-icon-64.png", "64x64"),
    ("icon/avalanche-icon-128.png", "128x128"),
    ("icon/avalanche-icon-256.png", "256x256"),
    ("icon/avalanche-icon-512.png", "512x512"),
]

# The wallpaper that ships as the default background.
WALLPAPER = "avalanche-wallpaper-dark-3840x2160-clean.png"

WP_PKG = "/usr/share/wallpapers/AvalancheOS"


def b64_block(path):
    with open(path, "rb") as f:
        data = f.read()
    b64 = base64.b64encode(data).decode()
    lines = "\n".join(b64[i:i + 76] for i in range(0, len(b64), 76))
    assert base64.b64decode(lines) == data, f"base64 round-trip failed for {path}"
    return lines, len(data)


def emit_png(out, src_rel, dest):
    block, nbytes = b64_block(os.path.join(ASSETS, src_rel))
    out.append(f'mkdir -p "$(dirname "{dest}")"')
    out.append(f"# {src_rel} -> {dest} ({nbytes} bytes)")
    out.append(f"base64 -d > \"{dest}\" << 'B64EOF'")
    out.append(block)
    out.append("B64EOF")
    out.append("")
    return nbytes


def main():
    out = []
    out.append("# avalanche-branding.ks — GENERATED by scripts/gen-branding-ks.py")
    out.append("# Do not edit by hand. Edit assets + the generator, then regenerate.")
    out.append("#")
    out.append("# Carries: logo icon (resolves os-release LOGO=) + default wallpaper.")
    out.append("")
    out.append("%post")
    out.append("")

    total = 0

    # ── Logo icon: install into the hicolor theme as `avalanche-logo-icon` ──
    out.append("# ── Logo icon (named avalanche-logo-icon, hicolor theme) ──────────────────")
    for src, size in ICONS:
        dest = f"/usr/share/icons/hicolor/{size}/apps/avalanche-logo-icon.png"
        total += emit_png(out, src, dest)
    # Refresh the icon cache so lookups by name succeed.
    out.append("gtk-update-icon-cache -f -t /usr/share/icons/hicolor 2>/dev/null || true")
    out.append('echo "AVALANCHE: logo icon installed (avalanche-logo-icon)"')
    out.append("")

    # ── Wallpaper: ship as a Plasma wallpaper package ─────────────────────────
    out.append("# ── Wallpaper package ─────────────────────────────────────────────────────")
    total += emit_png(out, WALLPAPER, f"{WP_PKG}/contents/images/3840x2160.png")

    out.append(f"cat > {WP_PKG}/metadata.json << 'METAEOF'")
    out.append('{')
    out.append('    "KPlugin": {')
    out.append('        "Id": "AvalancheOS",')
    out.append('        "Name": "Avalanche OS",')
    out.append('        "License": "CC-BY-SA-4.0",')
    out.append('        "Authors": [{ "Name": "Maxime Turcotte" }]')
    out.append('    }')
    out.append('}')
    out.append("METAEOF")
    out.append("")

    # ── Default desktop wallpaper for new users (/etc/skel) ───────────────────
    # Plasma reads a user's desktop layout from this file. Seeding it in
    # /etc/skel means a freshly-created live user starts with our wallpaper.
    out.append("mkdir -p /etc/skel/.config")
    out.append("cat > /etc/skel/.config/plasma-org.kde.plasma.desktop-appletsrc << 'APPLETEOF'")
    out.append("[Containments][1]")
    out.append("activityId=")
    out.append("formfactor=0")
    out.append("location=0")
    out.append("plugin=org.kde.plasma.folder")
    out.append("wallpaperplugin=org.kde.image")
    out.append("")
    out.append("[Containments][1][Wallpaper][org.kde.image][General]")
    out.append(f"Image=file://{WP_PKG}/")
    out.append("APPLETEOF")
    out.append("")

    # ── Lockscreen wallpaper (system-wide default via /etc/xdg) ───────────────
    out.append("cat > /etc/xdg/kscreenlockerrc << 'LOCKEOF'")
    out.append("[Greeter][Wallpaper][org.kde.image][General]")
    out.append(f"Image=file://{WP_PKG}/")
    out.append("LOCKEOF")
    out.append("")

    # ── Verify the embedded binaries are real images in the build log ─────────
    out.append(f'if file "{WP_PKG}/contents/images/3840x2160.png" | grep -q "PNG image data"; then')
    out.append('    echo "AVALANCHE: wallpaper OK ($(wc -c < ' + f'"{WP_PKG}/contents/images/3840x2160.png") bytes)"')
    out.append("else")
    out.append('    echo "AVALANCHE ERROR: wallpaper is not a valid PNG!"')
    out.append("fi")
    out.append("%end")
    out.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(out))

    print(f"Wrote {OUT}")
    print(f"  {len(ICONS)} icon sizes + 1 wallpaper, {total} bytes embedded, all round-trip verified.")


if __name__ == "__main__":
    main()
