#!/usr/bin/env python3
"""Generate the Plymouth %post kickstart fragment with the boot frames embedded.

Reads the theme descriptor, the script, and the three boot frames, then writes
avalanche-bootsplash.ks — a self-contained %post that recreates the theme inside
the image. Images are base64-encoded programmatically (no manual copy/paste, so
no truncation), and each block is verified to round-trip byte-for-byte.

Run from anywhere; paths are resolved relative to the project root.
"""
import base64
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, "assets", "bootsplash")
PLYMOUTH = os.path.join(ROOT, "plymouth")
OUT = os.path.join(ROOT, "avalanche-bootsplash.ks")

FRAMES = ["avalanche-boot-1.png", "avalanche-boot-2.png", "avalanche-boot-3.png"]
FRAME_DEST = ["boot-1.png", "boot-2.png", "boot-3.png"]


def b64_block(path):
    with open(path, "rb") as f:
        data = f.read()
    b64 = base64.b64encode(data).decode()
    lines = "\n".join(b64[i:i + 76] for i in range(0, len(b64), 76))
    # Verify round-trip before we trust it.
    assert base64.b64decode(lines) == data, f"base64 round-trip failed for {path}"
    return lines, len(data)


def read(path):
    with open(path) as f:
        return f.read()


def main():
    descriptor = read(os.path.join(PLYMOUTH, "avalanche.plymouth"))
    script = read(os.path.join(PLYMOUTH, "avalanche.script"))

    out = []
    out.append("# avalanche-bootsplash.ks — GENERATED by scripts/gen-bootsplash-ks.py")
    out.append("# Do not edit by hand. Edit plymouth/*.script + the PNG frames, then regenerate.")
    out.append("")
    out.append("%post")
    out.append("THEME_DIR=/usr/share/plymouth/themes/avalanche")
    out.append('mkdir -p "$THEME_DIR"')
    out.append("")
    out.append("# Theme descriptor")
    out.append('cat > "$THEME_DIR/avalanche.plymouth" << \'PLYEOF\'')
    out.append(descriptor.rstrip("\n"))
    out.append("PLYEOF")
    out.append("")
    out.append("# Animation script")
    out.append('cat > "$THEME_DIR/avalanche.script" << \'SCREOF\'')
    out.append(script.rstrip("\n"))
    out.append("SCREOF")
    out.append("")

    total = 0
    for src, dest in zip(FRAMES, FRAME_DEST):
        block, nbytes = b64_block(os.path.join(ASSETS, src))
        total += nbytes
        out.append(f"# {dest} ({nbytes} bytes)")
        out.append(f'base64 -d > "$THEME_DIR/{dest}" << \'B64EOF\'')
        out.append(block)
        out.append("B64EOF")
        out.append("")

    # Per-file sanity check in the build log.
    out.append("for img in boot-1.png boot-2.png boot-3.png; do")
    out.append('    if file "$THEME_DIR/$img" | grep -q "PNG image data"; then')
    out.append('        echo "AVALANCHE: $img OK ($(wc -c < "$THEME_DIR/$img") bytes)"')
    out.append("    else")
    out.append('        echo "AVALANCHE ERROR: $img is not a valid PNG!"')
    out.append("    fi")
    out.append("done")
    out.append("")
    out.append('plymouth-set-default-theme avalanche && echo "AVALANCHE: theme set OK" || echo "AVALANCHE ERROR: set-default-theme failed"')
    out.append('dracut -f && echo "AVALANCHE: dracut OK" || echo "AVALANCHE ERROR: dracut failed"')
    out.append("%end")
    out.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(out))

    print(f"Wrote {OUT}")
    print(f"  3 frames, {total} bytes total embedded, all round-trip verified.")


if __name__ == "__main__":
    main()
