#!/usr/bin/env python3
"""Generate avalanche-branding.ks with binary branding assets embedded.

Like gen-bootsplash-ks.py, %post can't read the host's assets/ dir, so any
binary (icons, wallpaper) must be base64-baked into the kickstart text. Each
block is verified to round-trip byte-for-byte before we trust it.

Embeds / writes:
  - the logo icon (4 sizes) as the named icon `avalanche-logo-icon`, so the
    LOGO= field in os-release (Layer 1) resolves.
  - the dark wallpaper as a proper Plasma wallpaper package.
  - a custom Look-and-Feel (global theme) package `org.avalanche.desktop`, and
    the /etc/xdg/kdedefaults/ cascade that makes it the SYSTEM DEFAULT.

Why the Look-and-Feel + kdedefaults route (and not /etc/skel + /etc/xdg/kdeglobals):
Plasma 5.24+ resolves "distro default" appearance from a high-precedence cascade
in /etc/xdg/kdedefaults/, populated by the active global-theme package. A bare
/etc/xdg/kdeglobals sits BELOW that and gets overridden by the stock Fedora
theme — which is exactly why our first attempt showed plain Breeze. The wallpaper
is referenced by its package DIRECTORY name (e.g. `AvalancheOS`), never a path,
so there are no fragile containment IDs to hardcode.

Run from anywhere; paths resolve relative to the project root.
"""
import base64
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, "assets")
OUT = os.path.join(ROOT, "avalanche-branding.ks")

# (source png, hicolor size dir) -> installed as avalanche-logo-icon.png
ICONS = [
    ("icon/avalanche-icon-64.png", "64x64"),
    ("icon/avalanche-icon-128.png", "128x128"),
    ("icon/avalanche-icon-256.png", "256x256"),
    ("icon/avalanche-icon-512.png", "512x512"),
]

# The wallpaper that ships as the default background.
WALLPAPER = "avalanche-wallpaper-dark-3840x2160-clean.png"

WP_PKG = "/usr/share/wallpapers/AvalancheOS"     # referenced by dir name "AvalancheOS"
LNF_ID = "org.avalanche.desktop"                  # Look-and-Feel package id == dir name
LNF_PKG = f"/usr/share/plasma/look-and-feel/{LNF_ID}"


def b64_block(path):
    with open(path, "rb") as f:
        data = f.read()
    b64 = base64.b64encode(data).decode()
    lines = "\n".join(b64[i:i + 76] for i in range(0, len(b64), 76))
    assert base64.b64decode(lines) == data, f"base64 round-trip failed for {path}"
    return lines, len(data)


def emit_png(out, src_rel, dest):
    block, nbytes = b64_block(os.path.join(ASSETS, src_rel))
    out.append(f'mkdir -p "$(dirname "{dest}")"')
    out.append(f"# {src_rel} -> {dest} ({nbytes} bytes)")
    out.append(f"base64 -d > \"{dest}\" << 'B64EOF'")
    out.append(block)
    out.append("B64EOF")
    out.append("")
    return nbytes


def heredoc(out, dest, body):
    """Emit a plain-text file via a quoted heredoc (no var expansion)."""
    out.append(f"mkdir -p \"$(dirname \"{dest}\")\"")
    out.append(f"cat > \"{dest}\" << 'TXTEOF'")
    out.append(body.rstrip("\n"))
    out.append("TXTEOF")
    out.append("")


def main():
    out = []
    out.append("# avalanche-branding.ks — GENERATED by scripts/gen-branding-ks.py")
    out.append("# Do not edit by hand. Edit assets + the generator, then regenerate.")
    out.append("#")
    out.append("# Carries: logo icon, wallpaper package, and the Look-and-Feel global")
    out.append("# theme + /etc/xdg/kdedefaults cascade that makes it the system default.")
    out.append("")
    out.append("%post")
    out.append("")

    total = 0

    # ── Logo icon: install into the hicolor theme as `avalanche-logo-icon` ──
    out.append("# ── Logo icon (named avalanche-logo-icon, hicolor theme) ──────────────────")
    for src, size in ICONS:
        dest = f"/usr/share/icons/hicolor/{size}/apps/avalanche-logo-icon.png"
        total += emit_png(out, src, dest)
    out.append("gtk-update-icon-cache -f -t /usr/share/icons/hicolor 2>/dev/null || true")
    out.append('echo "AVALANCHE: logo icon installed (avalanche-logo-icon)"')
    out.append("")

    # ── Start menu (Kickoff) icon ────────────────────────────────────────────
    # breeze-dark owns start-here-kde at multiple sizes under places/ and is
    # searched BEFORE hicolor, so we must override inside breeze-dark itself.
    # Also override hicolor as a fallback for other themes.
    out.append("# ── Start menu icon (Kickoff) — override in breeze-dark + hicolor ──────────")
    SVG = ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 124 110" width="124" height="110" role="img" aria-label="Avalanche OS mark">\n'
           '  <title>Avalanche OS</title>\n'
           '  <polygon points="42,14 8,86 74,86" fill="#E7EEF3"></polygon>\n'
           '  <polygon points="82,40 54,98 110,98" fill="#46627A"></polygon>\n'
           '  <polygon points="110,64 100,98 120,98" fill="#FF4D1C"></polygon>\n'
           '</svg>')
    # breeze-dark: all sizes × both icon names Plasma uses for Kickoff
    BREEZE_SIZES = ("16", "22", "24", "32", "64", "96")
    BREEZE_NAMES = ("start-here-kde", "start-here-kde-plasma")
    for size in BREEZE_SIZES:
        for name in BREEZE_NAMES:
            path = f"/usr/share/icons/breeze-dark/places/{size}/{name}.svg"
            heredoc(out, path, SVG)
    # hicolor: scalable fallback for other themes
    for icon_name in ("start-here", "start-here-kde", "start-here-fedora"):
        heredoc(out, f"/usr/share/icons/hicolor/scalable/apps/{icon_name}.svg", SVG)
    out.append("gtk-update-icon-cache -f -t /usr/share/icons/hicolor 2>/dev/null || true")
    out.append("gtk-update-icon-cache -f -t /usr/share/icons/breeze-dark 2>/dev/null || true")
    out.append("kbuildsycoca6 --noincremental 2>/dev/null || true")
    out.append('echo "AVALANCHE: start-here icons replaced in breeze-dark + hicolor"')
    out.append("")

    # ── Wallpaper: ship as a Plasma wallpaper package ─────────────────────────
    out.append("# ── Wallpaper package (referenced by dir name 'AvalancheOS') ──────────────")
    total += emit_png(out, WALLPAPER, f"{WP_PKG}/contents/images/3840x2160.png")
    heredoc(out, f"{WP_PKG}/metadata.json", """{
    "KPlugin": {
        "Id": "AvalancheOS",
        "Name": "Avalanche OS",
        "License": "CC-BY-SA-4.0",
        "Authors": [{ "Name": "Maxime Turcotte" }]
    }
}""")

    # ── Look-and-Feel (global theme) package ──────────────────────────────────
    out.append("# ── Look-and-Feel package org.avalanche.desktop ───────────────────────────")
    heredoc(out, f"{LNF_PKG}/metadata.json", """{
    "KPackageStructure": "Plasma/LookAndFeel",
    "KPlugin": {
        "Id": "org.avalanche.desktop",
        "Name": "Avalanche OS",
        "Description": "Avalanche OS — backcountry splitboard touring theme",
        "License": "CC-BY-SA-4.0",
        "Authors": [{ "Name": "Maxime Turcotte" }],
        "EnabledByDefault": true
    }
}""")
    # contents/defaults: two-token group headers, Image= resolves to the
    # wallpaper package dir name at /usr/share/wallpapers/AvalancheOS/.
    heredoc(out, f"{LNF_PKG}/contents/defaults", """[kdeglobals][KDE]
widgetStyle=Breeze

[kdeglobals][General]
ColorScheme=AvalancheOS

[kdeglobals][Icons]
Theme=breeze-dark

[plasmarc][Theme]
name=breeze-dark

[Wallpaper]
Image=AvalancheOS

[kcminputrc][Mouse]
cursorTheme=breeze_cursors

[kwinrc][org.kde.kdecoration2]
library=org.kde.breeze
theme=Breeze

[KSplash]
Theme=org.kde.Breeze""")

    # layout.js: sets wallpaper explicitly when LnF is applied to a new user.
    # Without this Plasma may fall back to the Fedora LnF layout which sets
    # the Fedora wallpaper. This mirrors what plasma-lookandfeel-fedora does.
    heredoc(out, f"{LNF_PKG}/contents/layouts/org.kde.plasma.desktop-layout.js",
            """loadTemplate("org.kde.plasma.desktop.defaultPanel")

var desktopsArray = desktopsForActivity(currentActivity());
for (var j = 0; j < desktopsArray.length; j++) {
    var desktop = desktopsArray[j];
    desktop.wallpaperPlugin = "org.kde.image";
    desktop.currentConfigGroup = ["Wallpaper", "org.kde.image", "General"];
    desktop.writeConfig("Image", "file:///usr/share/wallpapers/AvalancheOS/contents/images/3840x2160.png");
    desktop.currentConfigGroup = [];
}""")
    out.append('echo "AVALANCHE: look-and-feel installed (org.avalanche.desktop)"')
    out.append("")

    # ── kde-settings profile: the Fedora-native way to set the system LnF ───
    # /usr/share/kde-settings/kde-profile/default/xdg/kdeglobals is read by
    # Plasma on every new-user first login. It ships pointing to Fedora's LnF;
    # we patch it to point to ours so the wallpaper, icons, and color scheme
    # are applied correctly for users created by the Anaconda installer.
    out.append("# ── kde-settings profile (Fedora-native LnF hook for new users) ──────────")
    out.append("KDE_PROFILE=/usr/share/kde-settings/kde-profile/default/xdg/kdeglobals")
    out.append("if [ -f \"$KDE_PROFILE\" ]; then")
    out.append("    kwriteconfig6 --file \"$KDE_PROFILE\" --group KDE     --key LookAndFeelPackage org.avalanche.desktop")
    out.append("    kwriteconfig6 --file \"$KDE_PROFILE\" --group General  --key ColorScheme AvalancheOS")
    out.append("    kwriteconfig6 --file \"$KDE_PROFILE\" --group Icons    --key Theme breeze-dark")
    out.append('    echo "AVALANCHE: kde-settings profile patched -> org.avalanche.desktop"')
    out.append("else")
    out.append('    echo "AVALANCHE WARNING: kde-settings profile not found, skipping"')
    out.append("fi")
    out.append("")

    # ── System-default cascade: /etc/xdg/kdedefaults/ ─────────────────────────
    # Belt-and-suspenders: kdedefaults covers cases where the kde-settings
    # profile isn't read (e.g. the live session liveuser).
    out.append("# ── kdedefaults cascade (covers live session + belt-and-suspenders) ───────")
    heredoc(out, "/etc/xdg/kdedefaults/package", "org.avalanche.desktop")
    heredoc(out, "/etc/xdg/kdedefaults/kdeglobals", """[KDE]
LookAndFeelPackage=org.avalanche.desktop
widgetStyle=Breeze

[General]
ColorScheme=AvalancheOS

[Icons]
Theme=breeze-dark""")
    heredoc(out, "/etc/xdg/kdedefaults/plasmarc", """[Theme]
name=breeze-dark""")
    heredoc(out, "/etc/xdg/kdedefaults/kwinrc", """[org.kde.kdecoration2]
library=org.kde.breeze
theme=Breeze""")
    out.append('echo "AVALANCHE: kdedefaults cascade set (LookAndFeelPackage + ColorScheme)"')
    out.append("")

    # ── Lockscreen wallpaper ──────────────────────────────────────────────────
    out.append("# ── Lockscreen wallpaper (system-wide default via /etc/xdg) ───────────────")
    heredoc(out, "/etc/xdg/kscreenlockerrc", f"""[Greeter][Wallpaper][org.kde.image][General]
Image=file://{WP_PKG}/""")

    # ── First-login autostart: apply the Look-and-Feel for installed users ────
    # kdedefaults covers colors/icons/decoration but NOT the Plasma wallpaper
    # (which lives in plasma-org.kde.plasma.desktop-appletsrc, a runtime file
    # that is never seeded for newly created users). Running
    # plasma-apply-lookandfeel at first login is the official KDE way to push
    # the full theme — wallpaper included — to a brand-new user account.
    # The .desktop uses X-KDE-autostart-condition so it self-disables after one run.
    out.append("# ── First-login autostart (apply LnF for installed users) ────────────────")
    heredoc(out, "/etc/xdg/autostart/avalanche-firstlogin.desktop", """\
[Desktop Entry]
Name=Avalanche OS First Login Setup
Exec=/usr/local/bin/avalanche-firstlogin
Type=Application
X-KDE-autostart-condition=avalanche-firstloginrc:General:done:false""")
    out.append("cat > /usr/local/bin/avalanche-firstlogin << 'EOF'")
    out.append("#!/bin/bash")
    out.append("# Runs once on first Plasma login for each user.")
    out.append("# Applies the Avalanche OS Look-and-Feel (wallpaper, colors, icons, deco).")
    out.append("plasma-apply-lookandfeel --apply org.avalanche.desktop")
    out.append("kwriteconfig6 --file avalanche-firstloginrc --group General --key done true")
    out.append("EOF")
    out.append("chmod +x /usr/local/bin/avalanche-firstlogin")
    out.append('echo "AVALANCHE: first-login autostart installed"')
    out.append("")

    # ── Verify the embedded binary + the key default files in the build log ───
    out.append(f'if file "{WP_PKG}/contents/images/3840x2160.png" | grep -q "PNG image data"; then')
    out.append('    echo "AVALANCHE: wallpaper OK ($(wc -c < ' + f'"{WP_PKG}/contents/images/3840x2160.png") bytes)"')
    out.append("else")
    out.append('    echo "AVALANCHE ERROR: wallpaper is not a valid PNG!"')
    out.append("fi")
    out.append('if [ "$(cat /etc/xdg/kdedefaults/package)" = "org.avalanche.desktop" ] && [ -f "' + f'{LNF_PKG}/contents/defaults" ]; then')
    out.append('    echo "AVALANCHE: kdedefaults + look-and-feel verified"')
    out.append("else")
    out.append('    echo "AVALANCHE ERROR: kdedefaults/look-and-feel missing!"')
    out.append("fi")
    out.append("%end")
    out.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(out))

    print(f"Wrote {OUT}")
    print(f"  {len(ICONS)} icon sizes + 1 wallpaper, {total} bytes embedded, all round-trip verified.")
    print(f"  + look-and-feel package {LNF_ID} and /etc/xdg/kdedefaults cascade.")


if __name__ == "__main__":
    main()
